services:
  vnc:
    image: lcas.lincoln.ac.uk/vnc
    volumes:
      - x11:/tmp/.X11-unix
    networks:
      - ros_net
    environment:
      - VNC_WALLPAPER=gir
    stdin_open: true
    tty: true
    ipc: shareable

  develop:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      target: devcontainer
    volumes:
      - ../:/workspace
      - x11:/tmp/.X11-unix
      - colcon_build:/workspace/build
      - colcon_install:/workspace/install
      - colcon_log:/workspace/log
    stdin_open: true
    tty: true
    networks:
      - ros_net
    depends_on: 
      - vnc
    environment:
      - DISPLAY=:1.0
      - ROS_DOMAIN_ID=10
    ipc: "service:vnc" 

volumes:
  x11:
  colcon_build:
  colcon_install:
  colcon_log:

networks:
  ros_net:
