name: ros CI

on:
  push:
    # you may want to configure the branches that this should be run on here.
    branches: [ "main" ]
  pull_request:

jobs:
  test_docker: # On Linux, iterates on defined ROS 2 distributions.
    runs-on: ubuntu-latest
    strategy:
      matrix:

        # Define the Docker image(s) associated with each ROS distribution.
        # The include syntax allows additional variables to be defined, like
        # docker_image in this case. See documentation:
        # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-configurations-in-a-matrix-build
        #
        # Platforms are defined in REP 2000:
        # https://ros.org/reps/rep-2000.html
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: ubuntu:noble
            ros_distribution: jazzy

          # # Rolling Ridley (No End-Of-Life)
          # - docker_image: ubuntu:jammy
          #   ros_distribution: rolling
          #   ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - uses: actions/checkout@v6

      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.7

      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          import-token: ${{ github.token }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
